RF_SDK: nextlimit::Color4< T > Class Template Reference
nextlimit::Color4< T > Class Template Reference
#include <nl_color4.h>
Public Member Functions
Life Cycle:
Color4 (void)
Constructor from void.
Color4 (const Color4 &c)
Color4 (const Tuple4_BYTE &rgba)
Color4 (const Tuple3_BYTE &rgb)
Color4 (const Vector4< T > &v)
Color4 (const Vector3< T > &v, const T &a=1)
Color4 (const T &r, const T &g, const T &b, const T &a=1)
template<class U >
Color4 (const U &r, const U &g, const U &b, const U &a)
template<class U >
Color4 (const U &r, const U &g, const U &b)
Color4 (const NL_BYTE &r, const NL_BYTE &g, const NL_BYTE &b, const NL_BYTE &a)
Color4 (const NL_BYTE &r, const NL_BYTE &g, const NL_BYTE &b)
Color4 (const NL_INT &r, const NL_INT &g, const NL_INT &b, const NL_INT &a)
Color4 (const NL_INT &r, const NL_INT &g, const NL_INT &b)
Color4 (const T &gray)
~Color4 (void)
Destructor.
Access:
const Vector4< T > & getVector4 () const
Vector4< T > & getVector4 ()
const Vector4< T > & v4 () const
Vector4< T > & v4 ()
const Tuple4< T > & getTuple4 () const
Tuple4< T > & refTuple4 ()
const Vector3< T > & getVector3 () const
Vector3< T > & getVector3 ()
const Vector3< T > & v3 () const
Vector3< T > & v3 ()
NL_BOOL isValid (void) const
template<class I >
T & operator[] (const I &i)
template<class I >
const T & operator[] (const I &i) const
const T & getRed (void) const
template<class M >
const M getRedDiscrete (void) const
const T & getGreen (void) const
template<class M >
const M getGreenDiscrete (void) const
const T & getBlue (void) const
template<class M >
const M getBlueDiscrete (void) const
const T & getAlpha (void) const
template<class M >
const M getAlphaDiscrete (void) const
T * castToPtr ()
castToPtr
const T * castToPtr () const
castToPtr
Set:
void set (const T &r, const T &g, const T &b, const T &a=T(1))
template<class U >
void setInteger (const U &r, const U &g, const U &b, const U &a)
template<class U >
void setInteger (const U &r, const U &g, const U &b)
template<class U >
void set (const Tuple4< U > &t)
template<class U >
void setInteger (const Tuple4< U > &t)
template<class U >
void set (const Tuple3< U > &t)
template<class U >
void setInteger (const Tuple3< U > &t)
void set (const Color4 &v)
void setGray (const T &gray, const T &alpha=T(1))
template<class N >
void setCast (const N &r, const N &g, const N &b, const N &a)
Set components casting to T.
void setRed (const T &r)
void setGreen (const T &g)
void setBlue (const T &b)
void setAlpha (const T &a)
void setZero (void)
Set the color components to 0.
void setSum (const Color4 &c, const Color4 &d)
Set sum of colors c and d Allowed use this as c or d.
void setSub (const Color4 &c, const Color4 &d)
Set the difference of colors c and d. Allowed use this as d or d.
void setInterpolation (const Color4 &c, const Color4 &d, const T &rate)
Operators: =
void operator= (const Color4 &c)
Assignment operator.
Operators: Compare
NL_BOOL operator== (const Color4 &c) const
Equality operator.
Operators: +, -
Color4 operator- (void) const
Negate color components.
Color4 operator+ (const Color4 &c) const
Return Sum.
Color4 operator- (const Color4 &c) const
Return Difference.
void operator+= (const Color4 &c)
Add other color to this.
void operator-= (const Color4 &c)
Subtract other color to this.
Color4 operator* (const Color4 &c) const
Multiply color components.
void operator*= (const Color4 &c)
Multiply this by color components.
Color4 operator/ (const Color4 &c) const
Divide color components.
void operator/= (const Color4 &c)
Divide this by color components.
Operators: *, /
Color4 operator* (const T &scalar) const
Multiply color by scalar.
Color4 operator/ (const T &scalar) const
Divide color by scalar.
void operator*= (const T &scalar)
Multiply this by scalar.
void operator/= (const T &scalar)
Divide this color by scalar.
Operations:
void negate ()
Negate the color.
void scale (const Color4 &c)
Scale every coord of this with every coord of v.
Static Public Member Functions
Access Static:
static Color4 & castFromPtr (T *pointer)
static const Color4 & castFromPtr (const T *pointer)
static const Color4 & colorWhite ()
static const Color4 & colorBlack ()
static const Color4 & colorRed ()
static const Color4 & colorGreen ()
static const Color4 & colorBlue ()
static const Color4 & colorYellow ()
static const Color4 & colorCyan ()
static const Color4 & colorPink ()
static const Color4 & colorBasic (const NL_INDEX &i)
static Color4 colorBasic49 (const NL_INDEX &i)
static const Color4 & colorBasicRand ()
Public Attributes
T r_
T g_
T b_
T a_
Detailed Description
template<class T>
class nextlimit::Color4< T >
Definition at line 23 of file nl_color4.h.
Constructor & Destructor Documentation
template<class T> nextlimit::Color4< T >::Color4 (void) [inline]
Constructor from void.
Definition at line 33 of file nl_color4.h.
Referenced by nextlimit::Color4< T >::operator*(), nextlimit::Color4< T >::operator+(), nextlimit::Color4< T >::operator-(), and nextlimit::Color4< T >::operator/().
template<class T> nextlimit::Color4< T >::Color4 (const Color4< T > & c) [inline]
Constructor from another color.
Parameters:
v [in] Source color.
Definition at line 40 of file nl_color4.h.
References nextlimit::Color4< T >::isValid().
template<class T> nextlimit::Color4< T >::Color4 (const Tuple4_BYTE & rgba) [inline, explicit]
Constructor from byte values.
Parameters:
rgba [in] rgba in range 0..255.
Definition at line 50 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> nextlimit::Color4< T >::Color4 (const Tuple3_BYTE & rgb) [inline, explicit]
Constructor from byte values.
Parameters:
rgb [in] rgb in range 0..255.
Definition at line 57 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> nextlimit::Color4< T >::Color4 (const Vector4< T > & v) [inline, explicit]
Constructor from vector4
Parameters:
v4 [in] Source vector4.
Definition at line 64 of file nl_color4.h.
References nextlimit::Color4< T >::isValid().
template<class T> nextlimit::Color4< T >::Color4 (const Vector3< T > & v, const T & a = 1) [inline, explicit]
Constructor from vector3 and alpha
Parameters:
v3 [in] Source vector3.
a [in] Source alpha.
Definition at line 75 of file nl_color4.h.
References nextlimit::Color4< T >::isValid().
template<class T> nextlimit::Color4< T >::Color4 (const T & r, const T & g, const T & b, const T & a = 1) [inline]
Constructor from the color components.
Parameters:
r [in]
g [in]
b [in]
a [in]
Definition at line 88 of file nl_color4.h.
References nextlimit::Color4< T >::isValid().
template<class T> template<class U > nextlimit::Color4< T >::Color4 (const U & r, const U & g, const U & b, const U & a) [inline]
Constructor from the color FLOATING components
Parameters:
r [in]
g [in]
b [in]
Definition at line 104 of file nl_color4.h.
References nextlimit::Color4< T >::isValid().
template<class T> template<class U > nextlimit::Color4< T >::Color4 (const U & r, const U & g, const U & b) [inline]
Constructor from the color FLOATING components
Parameters:
r [in]
g [in]
b [in]
a [in]
Definition at line 122 of file nl_color4.h.
References nextlimit::Color4< T >::isValid().
template<class T> nextlimit::Color4< T >::Color4 (const NL_BYTE & r, const NL_BYTE & g, const NL_BYTE & b, const NL_BYTE & a) [inline]
Constructor from the color NL_BYTE components
Parameters:
r [in]
g [in]
b [in]
a [in]
Definition at line 138 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> nextlimit::Color4< T >::Color4 (const NL_BYTE & r, const NL_BYTE & g, const NL_BYTE & b) [inline]
Constructor from the color NL_BYTE components
Parameters:
r [in]
g [in]
b [in]
Definition at line 150 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> nextlimit::Color4< T >::Color4 (const NL_INT & r, const NL_INT & g, const NL_INT & b, const NL_INT & a) [inline]
Constructor from the color NL_INT components
Parameters:
r [in]
g [in]
b [in]
a [in]
Definition at line 162 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> nextlimit::Color4< T >::Color4 (const NL_INT & r, const NL_INT & g, const NL_INT & b) [inline]
Constructor from the color NL_INT components
Parameters:
r [in]
g [in]
b [in]
Definition at line 174 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> nextlimit::Color4< T >::Color4 (const T & gray) [inline, explicit]
Constructor from a value to initialize all the components.
Parameters:
c [in] Value for the three components.
Definition at line 183 of file nl_color4.h.
References nextlimit::Color4< T >::isValid().
template<class T> nextlimit::Color4< T >::~Color4 (void) [inline]
Destructor.
Definition at line 192 of file nl_color4.h.
Member Function Documentation
template<class T> static Color4& nextlimit::Color4< T >::castFromPtr (T * pointer) [inline, static]
Definition at line 296 of file nl_color4.h.
Referenced by nextlimit::Color4< T >::colorBlack(), nextlimit::Color4< T >::colorBlue(), nextlimit::Color4< T >::colorCyan(), nextlimit::Color4< T >::colorGreen(), nextlimit::Color4< T >::colorPink(), nextlimit::Color4< T >::colorRed(), nextlimit::Color4< T >::colorWhite(), and nextlimit::Color4< T >::colorYellow().
template<class T> static const Color4& nextlimit::Color4< T >::castFromPtr (const T * pointer) [inline, static]
Definition at line 297 of file nl_color4.h.
template<class T> const T* nextlimit::Color4< T >::castToPtr () const [inline]
castToPtr
Definition at line 288 of file nl_color4.h.
template<class T> T* nextlimit::Color4< T >::castToPtr () [inline]
castToPtr
Definition at line 285 of file nl_color4.h.
template<class T> static const Color4& nextlimit::Color4< T >::colorBasic (const NL_INDEX & i) [inline, static]
Definition at line 310 of file nl_color4.h.
References nextlimit::Color4< T >::colorBlue(), nextlimit::Color4< T >::colorCyan(), nextlimit::Color4< T >::colorGreen(), nextlimit::Color4< T >::colorPink(), nextlimit::Color4< T >::colorRed(), nextlimit::Color4< T >::colorWhite(), and nextlimit::Color4< T >::colorYellow().
Referenced by nextlimit::Color4< T >::colorBasic49(), and nextlimit::Color4< T >::colorBasicRand().
template<class T> static Color4 nextlimit::Color4< T >::colorBasic49 (const NL_INDEX & i) [inline, static]
Definition at line 327 of file nl_color4.h.
References nextlimit::Color4< T >::colorBasic(), and nextlimit::Color4< T >::setInterpolation().
template<class T> static const Color4& nextlimit::Color4< T >::colorBasicRand () [inline, static]
Definition at line 340 of file nl_color4.h.
References nextlimit::Color4< T >::colorBasic().
template<class T> static const Color4& nextlimit::Color4< T >::colorBlack () [inline, static]
Definition at line 300 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::setZero().
template<class T> static const Color4& nextlimit::Color4< T >::colorBlue () [inline, static]
Definition at line 304 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::colorBasic().
template<class T> static const Color4& nextlimit::Color4< T >::colorCyan () [inline, static]
Definition at line 307 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::colorBasic().
template<class T> static const Color4& nextlimit::Color4< T >::colorGreen () [inline, static]
Definition at line 303 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::colorBasic().
template<class T> static const Color4& nextlimit::Color4< T >::colorPink () [inline, static]
Definition at line 308 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::colorBasic().
template<class T> static const Color4& nextlimit::Color4< T >::colorRed () [inline, static]
Definition at line 302 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::colorBasic().
template<class T> static const Color4& nextlimit::Color4< T >::colorWhite () [inline, static]
Definition at line 299 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::colorBasic().
template<class T> static const Color4& nextlimit::Color4< T >::colorYellow () [inline, static]
Definition at line 306 of file nl_color4.h.
References nextlimit::Color4< T >::castFromPtr().
Referenced by nextlimit::Color4< T >::colorBasic().
template<class T> const T& nextlimit::Color4< T >::getAlpha (void) const [inline]
Returns:
alpha
Definition at line 276 of file nl_color4.h.
References nextlimit::Color4< T >::a_.
template<class T> template<class M > const M nextlimit::Color4< T >::getAlphaDiscrete (void) const [inline]
Definition at line 279 of file nl_color4.h.
References nextlimit::Color4< T >::a_.
template<class T> const T& nextlimit::Color4< T >::getBlue (void) const [inline]
Returns:
get blue color
Definition at line 267 of file nl_color4.h.
References nextlimit::Color4< T >::b_.
template<class T> template<class M > const M nextlimit::Color4< T >::getBlueDiscrete (void) const [inline]
Definition at line 270 of file nl_color4.h.
References nextlimit::Color4< T >::b_.
template<class T> const T& nextlimit::Color4< T >::getGreen (void) const [inline]
Returns:
get green color
Definition at line 258 of file nl_color4.h.
References nextlimit::Color4< T >::g_.
template<class T> template<class M > const M nextlimit::Color4< T >::getGreenDiscrete (void) const [inline]
Definition at line 261 of file nl_color4.h.
References nextlimit::Color4< T >::g_.
template<class T> const T& nextlimit::Color4< T >::getRed (void) const [inline]
Returns:
get red color
Definition at line 249 of file nl_color4.h.
References nextlimit::Color4< T >::r_.
template<class T> template<class M > const M nextlimit::Color4< T >::getRedDiscrete (void) const [inline]
Definition at line 252 of file nl_color4.h.
References nextlimit::Color4< T >::r_.
template<class T> const Tuple4<T>& nextlimit::Color4< T >::getTuple4 () const [inline]
Returns:
as const Tuple4.
Definition at line 213 of file nl_color4.h.
References nextlimit::Color4< T >::getTuple4(), and nextlimit::Color4< T >::v4().
Referenced by nextlimit::Color4< T >::getTuple4(), and nextlimit::Color4< T >::isValid().
template<class T> Vector3<T>& nextlimit::Color4< T >::getVector3 () [inline]
Returns:
as Vector3.
Definition at line 222 of file nl_color4.h.
References nextlimit::Color4< T >::v3(), and nextlimit::Color4< T >::v4().
template<class T> const Vector3<T>& nextlimit::Color4< T >::getVector3 () const [inline]
Returns:
as const Vector3.
Definition at line 219 of file nl_color4.h.
References nextlimit::Color4< T >::v3(), and nextlimit::Color4< T >::v4().
Referenced by nextlimit::Color4< T >::v3().
template<class T> const Vector4<T>& nextlimit::Color4< T >::getVector4 () const [inline]
Returns:
as const Vector4.
Definition at line 201 of file nl_color4.h.
Referenced by nextlimit::Color4< T >::v4().
template<class T> Vector4<T>& nextlimit::Color4< T >::getVector4 () [inline]
Returns:
as Vector4.
Definition at line 204 of file nl_color4.h.
template<class T> NL_BOOL nextlimit::Color4< T >::isValid (void) const [inline]
Returns:
true if is Valid
Definition at line 231 of file nl_color4.h.
References nextlimit::Color4< T >::a_, nextlimit::Color4< T >::b_, nextlimit::Color4< T >::g_, nextlimit::Color4< T >::getTuple4(), and nextlimit::Color4< T >::r_.
Referenced by nextlimit::Color4< T >::Color4(), nextlimit::Color4< T >::operator+(), nextlimit::Color4< T >::operator+=(), nextlimit::Color4< T >::operator-(), nextlimit::Color4< T >::operator-=(), nextlimit::Color4< T >::operator=(), nextlimit::Color4< T >::scale(), nextlimit::Color4< T >::setInteger(), nextlimit::Color4< T >::setInterpolation(), nextlimit::Color4< T >::setSub(), and nextlimit::Color4< T >::setSum().
template<class T> void nextlimit::Color4< T >::negate () [inline]
Negate the color.
Definition at line 662 of file nl_color4.h.
References nextlimit::Color4< T >::v3().
template<class T> Color4 nextlimit::Color4< T >::operator* (const T & scalar) const [inline]
Multiply color by scalar.
Definition at line 631 of file nl_color4.h.
References nextlimit::Color4< T >::Color4(), and nextlimit::Color4< T >::v3().
template<class T> Color4 nextlimit::Color4< T >::operator* (const Color4< T > & c) const [inline]
Multiply color components.
Definition at line 592 of file nl_color4.h.
References nextlimit::Color4< T >::v4().
template<class T> void nextlimit::Color4< T >::operator*= (const Color4< T > & c) [inline]
Multiply this by color components.
Definition at line 600 of file nl_color4.h.
References nextlimit::Color4< T >::b_, nextlimit::Color4< T >::g_, and nextlimit::Color4< T >::r_.
template<class T> void nextlimit::Color4< T >::operator*= (const T & scalar) [inline]
Multiply this by scalar.
Definition at line 643 of file nl_color4.h.
References nextlimit::Color4< T >::v3().
template<class T> Color4 nextlimit::Color4< T >::operator+ (const Color4< T > & c) const [inline]
Return Sum.
Definition at line 564 of file nl_color4.h.
References nextlimit::Color4< T >::Color4(), nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v3().
template<class T> void nextlimit::Color4< T >::operator+= (const Color4< T > & c) [inline]
Add other color to this.
Definition at line 578 of file nl_color4.h.
References nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v3().
template<class T> Color4 nextlimit::Color4< T >::operator- (void) const [inline]
Negate color components.
Definition at line 558 of file nl_color4.h.
References nextlimit::Color4< T >::Color4(), and nextlimit::Color4< T >::v4().
template<class T> Color4 nextlimit::Color4< T >::operator- (const Color4< T > & c) const [inline]
Return Difference.
Definition at line 571 of file nl_color4.h.
References nextlimit::Color4< T >::Color4(), nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v3().
template<class T> void nextlimit::Color4< T >::operator-= (const Color4< T > & c) [inline]
Subtract other color to this.
Definition at line 585 of file nl_color4.h.
References nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v3().
template<class T> Color4 nextlimit::Color4< T >::operator/ (const Color4< T > & c) const [inline]
Divide color components.
Definition at line 608 of file nl_color4.h.
References nextlimit::Color4< T >::v4().
template<class T> Color4 nextlimit::Color4< T >::operator/ (const T & scalar) const [inline]
Divide color by scalar.
Definition at line 637 of file nl_color4.h.
References nextlimit::Color4< T >::Color4(), and nextlimit::Color4< T >::v3().
template<class T> void nextlimit::Color4< T >::operator/= (const Color4< T > & c) [inline]
Divide this by color components.
Definition at line 616 of file nl_color4.h.
References nextlimit::Color4< T >::b_, nextlimit::Color4< T >::g_, and nextlimit::Color4< T >::r_.
template<class T> void nextlimit::Color4< T >::operator/= (const T & scalar) [inline]
Divide this color by scalar.
Definition at line 649 of file nl_color4.h.
References nextlimit::Color4< T >::v3().
template<class T> void nextlimit::Color4< T >::operator= (const Color4< T > & c) [inline]
Assignment operator.
Definition at line 531 of file nl_color4.h.
References nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v4().
Referenced by nextlimit::Color4< T >::set(), and nextlimit::Color4< T >::setZero().
template<class T> NL_BOOL nextlimit::Color4< T >::operator== (const Color4< T > & c) const [inline]
Equality operator.
Definition at line 545 of file nl_color4.h.
References nextlimit::Color4< T >::v4().
template<class T> template<class I > T& nextlimit::Color4< T >::operator[] (const I & i) [inline]
Returns:
reference coord at index "i".
Definition at line 242 of file nl_color4.h.
References nextlimit::Color4< T >::v4().
template<class T> template<class I > const T& nextlimit::Color4< T >::operator[] (const I & i) const [inline]
Returns:
const reference coord at index "i".
Definition at line 246 of file nl_color4.h.
References nextlimit::Color4< T >::v4().
template<class T> Tuple4<T>& nextlimit::Color4< T >::refTuple4 () [inline]
Returns:
as Tuple4.
Definition at line 216 of file nl_color4.h.
References nextlimit::Color4< T >::refTuple4(), and nextlimit::Color4< T >::v4().
Referenced by nextlimit::Color4< T >::refTuple4().
template<class T> void nextlimit::Color4< T >::scale (const Color4< T > & c) [inline]
Scale every coord of this with every coord of v.
Definition at line 668 of file nl_color4.h.
References nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v3().
template<class T> template<class U > void nextlimit::Color4< T >::set (const Tuple3< U > & t) [inline]
Set the color components values.
Parameters:
t [in] tuple3 of floats
Definition at line 424 of file nl_color4.h.
template<class T> void nextlimit::Color4< T >::set (const T & r, const T & g, const T & b, const T & a = T(1)) [inline]
Set the color components values.
Parameters:
r [in] X color coord.
g [in] Y color coord.
b [in] Z color coord.
Definition at line 356 of file nl_color4.h.
References nextlimit::Color4< T >::v4().
template<class T> template<class U > void nextlimit::Color4< T >::set (const Tuple4< U > & t) [inline]
Set the color components values.
Parameters:
t [in] tuple4 of floats
Definition at line 408 of file nl_color4.h.
template<class T> void nextlimit::Color4< T >::set (const Color4< T > & v) [inline]
Set to other color.
Parameters:
v [in] color desired .
Definition at line 439 of file nl_color4.h.
References nextlimit::Color4< T >::operator=().
template<class T> void nextlimit::Color4< T >::setAlpha (const T & a) [inline]
Parameters:
a [in] New value for the alpha component
Definition at line 489 of file nl_color4.h.
References nextlimit::Color4< T >::a_.
template<class T> void nextlimit::Color4< T >::setBlue (const T & b) [inline]
Parameters:
b [in] New value for the blue component
Definition at line 482 of file nl_color4.h.
References nextlimit::Color4< T >::b_.
template<class T> template<class N > void nextlimit::Color4< T >::setCast (const N & r, const N & g, const N & b, const N & a) [inline]
Set components casting to T.
Definition at line 459 of file nl_color4.h.
References nextlimit::Color4< T >::v4().
template<class T> void nextlimit::Color4< T >::setGray (const T & gray, const T & alpha = T(1)) [inline]
Set all rgb values to gray
Parameters:
gray [in] desired value for all the components.
Definition at line 447 of file nl_color4.h.
References nextlimit::Color4< T >::a_, nextlimit::Color4< T >::b_, nextlimit::Color4< T >::g_, and nextlimit::Color4< T >::r_.
template<class T> void nextlimit::Color4< T >::setGreen (const T & g) [inline]
Parameters:
g [in] New value for the green component
Definition at line 475 of file nl_color4.h.
References nextlimit::Color4< T >::g_.
template<class T> template<class U > void nextlimit::Color4< T >::setInteger (const Tuple3< U > & t) [inline]
Set the color components values.
Parameters:
t [in] tuple3 of integers
Definition at line 432 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> template<class U > void nextlimit::Color4< T >::setInteger (const U & r, const U & g, const U & b, const U & a) [inline]
Constructor from the color INTEGER components
Parameters:
r [in]
g [in]
b [in]
a [in]
Definition at line 374 of file nl_color4.h.
References nextlimit::Color4< T >::a_, nextlimit::Color4< T >::b_, nextlimit::Color4< T >::g_, nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::r_.
Referenced by nextlimit::Color4< T >::Color4(), and nextlimit::Color4< T >::setInteger().
template<class T> template<class U > void nextlimit::Color4< T >::setInteger (const U & r, const U & g, const U & b) [inline]
Constructor from the color INTEGER components
Parameters:
r [in]
g [in]
b [in]
a [in]
Definition at line 393 of file nl_color4.h.
References nextlimit::Color4< T >::a_, nextlimit::Color4< T >::b_, nextlimit::Color4< T >::g_, nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::r_.
template<class T> template<class U > void nextlimit::Color4< T >::setInteger (const Tuple4< U > & t) [inline]
Set the color components values.
Parameters:
t [in] tuple4 of integers
Definition at line 416 of file nl_color4.h.
References nextlimit::Color4< T >::setInteger().
template<class T> void nextlimit::Color4< T >::setInterpolation (const Color4< T > & c, const Color4< T > & d, const T & rate) [inline]
Set the color interpolated c * (1 - rate) + d * rate
Parameters:
d [in] color to set if rate == 0
d [in] color to set if rate == 1
rate [in] parameter of interpolation
Definition at line 516 of file nl_color4.h.
References nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v4().
Referenced by nextlimit::Color4< T >::colorBasic49().
template<class T> void nextlimit::Color4< T >::setRed (const T & r) [inline]
Parameters:
r [in] New value for the red component
Definition at line 468 of file nl_color4.h.
References nextlimit::Color4< T >::r_.
template<class T> void nextlimit::Color4< T >::setSub (const Color4< T > & c, const Color4< T > & d) [inline]
Set the difference of colors c and d. Allowed use this as d or d.
Definition at line 506 of file nl_color4.h.
References nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v4().
template<class T> void nextlimit::Color4< T >::setSum (const Color4< T > & c, const Color4< T > & d) [inline]
Set sum of colors c and d Allowed use this as c or d.
Definition at line 499 of file nl_color4.h.
References nextlimit::Color4< T >::isValid(), and nextlimit::Color4< T >::v4().
template<class T> void nextlimit::Color4< T >::setZero (void) [inline]
Set the color components to 0.
Definition at line 496 of file nl_color4.h.
References nextlimit::Color4< T >::colorBlack(), and nextlimit::Color4< T >::operator=().
template<class T> const Vector3<T>& nextlimit::Color4< T >::v3 () const [inline]
Returns:
as const Vector3.
Definition at line 225 of file nl_color4.h.
References nextlimit::Color4< T >::getVector3().
Referenced by nextlimit::Color4< T >::getVector3(), nextlimit::Color4< T >::negate(), nextlimit::Color4< T >::operator*(), nextlimit::Color4< T >::operator*=(), nextlimit::Color4< T >::operator+(), nextlimit::Color4< T >::operator+=(), nextlimit::Color4< T >::operator-(), nextlimit::Color4< T >::operator-=(), nextlimit::Color4< T >::operator/(), nextlimit::Color4< T >::operator/=(), and nextlimit::Color4< T >::scale().
template<class T> Vector3<T>& nextlimit::Color4< T >::v3 () [inline]
Returns:
as Vector3.
Definition at line 228 of file nl_color4.h.
References nextlimit::Color4< T >::getVector3().
template<class T> Vector4<T>& nextlimit::Color4< T >::v4 () [inline]
Returns:
as Vector4.
Definition at line 210 of file nl_color4.h.
References nextlimit::Color4< T >::getVector4().
template<class T> const Vector4<T>& nextlimit::Color4< T >::v4 () const [inline]
Returns:
as const Vector4.
Definition at line 207 of file nl_color4.h.
References nextlimit::Color4< T >::getVector4().
Referenced by nextlimit::Color4< T >::getTuple4(), nextlimit::Color4< T >::getVector3(), nextlimit::Color4< T >::operator*(), nextlimit::Color4< T >::operator-(), nextlimit::Color4< T >::operator/(), nextlimit::Color4< T >::operator=(), nextlimit::Color4< T >::operator==(), nextlimit::operator>(), nextlimit::Color4< T >::operator[](), nextlimit::Color4< T >::refTuple4(), nextlimit::Color4< T >::set(), nextlimit::Color4< T >::setCast(), nextlimit::Color4< T >::setInterpolation(), nextlimit::Color4< T >::setSub(), and nextlimit::Color4< T >::setSum().
Member Data Documentation
template<class T> T nextlimit::Color4< T >::a_
Definition at line 683 of file nl_color4.h.
Referenced by nextlimit::Color4< T >::getAlpha(), nextlimit::Color4< T >::getAlphaDiscrete(), nextlimit::Color4< T >::isValid(), nextlimit::NL_set(), nextlimit::Color4< T >::setAlpha(), nextlimit::Color4< T >::setGray(), and nextlimit::Color4< T >::setInteger().
template<class T> T nextlimit::Color4< T >::b_
Definition at line 682 of file nl_color4.h.
Referenced by nextlimit::Color4< T >::getBlue(), nextlimit::Color4< T >::getBlueDiscrete(), nextlimit::Color4< T >::isValid(), nextlimit::NL_set(), nextlimit::Color4< T >::operator*=(), nextlimit::Color4< T >::operator/=(), nextlimit::Color4< T >::setBlue(), nextlimit::Color4< T >::setGray(), and nextlimit::Color4< T >::setInteger().
template<class T> T nextlimit::Color4< T >::g_
Definition at line 681 of file nl_color4.h.
Referenced by nextlimit::Color4< T >::getGreen(), nextlimit::Color4< T >::getGreenDiscrete(), nextlimit::Color4< T >::isValid(), nextlimit::NL_set(), nextlimit::Color4< T >::operator*=(), nextlimit::Color4< T >::operator/=(), nextlimit::Color4< T >::setGray(), nextlimit::Color4< T >::setGreen(), and nextlimit::Color4< T >::setInteger().
template<class T> T nextlimit::Color4< T >::r_
Definition at line 680 of file nl_color4.h.
Referenced by nextlimit::Color4< T >::getRed(), nextlimit::Color4< T >::getRedDiscrete(), nextlimit::Color4< T >::isValid(), nextlimit::NL_set(), nextlimit::Color4< T >::operator*=(), nextlimit::Color4< T >::operator/=(), nextlimit::Color4< T >::setGray(), nextlimit::Color4< T >::setInteger(), and nextlimit::Color4< T >::setRed().
The documentation for this class was generated from the following file:
E:/Projects/NextLimit/RealFlow/RFSdk/include/rf_sdk/sdk/nl_color4.h